openapi: 3.0.4

info:
  title: AlgaShop - Ordering
  version: "1.0"

servers:
  - description: Development
    url: "http://localhost:8080"
  - description: Production
    url: "https://api.algashop.com"

paths:
  /api/v1/customers:
    post:
      description: Register a new customer
      tags:
       - Customers
    get:
      description: List customers
      tags:
        - Customers
  /api/v1/customers/{customerId}:
    get:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: '019bbc17-9611-77df-ba51-a2290ca9d5ae'
      description: Get one customer by id
      tags:
        - Customers
    put:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: '019bbc17-9611-77df-ba51-a2290ca9d5ae'
      description: Edit customer
      tags:
        - Customers
    delete:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: '019bbc17-9611-77df-ba51-a2290ca9d5ae'
      description: Delete customer
      tags:
        - Customers

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          example: "019bbc17-9611-77df-ba51-a2290ca9d5ae"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          example: "johndoe@email.com"
        document:
          type: string
          example: "12345"
        phone:
          type: string
          example: "11211244545"
        birthdate:
          type: string
          format: date
          example: "1991-07-05"
        loyaltyPoints:
          type: number
          example: 10
        registeredAd:
          type: string
          format: date-time
          example: "2026-01-04T00:12:45Z"
        archivedAt:
          type: string
          format: date-time
          example: "2026-01-10T13:12:45Z"
        promotionNotificationsAllowed:
          type: boolean
          example: false
        archived:
          type: boolean
          example: false
        address:
          $ref: "#/components/schemas/Address"
    Address:
       type: object
       properties:
        street:
          type: string
          example: "Bourbon Street"
        number:
          type: string
          example: "2500"
        complement:
          type: string
          example: "apt 201"
        neighborhood:
          type: string
          example: "Norh Ville"
        city:
          type: string
          example: "Yostfort"
        state:
          type: string
          example: "South Carolina"
        zipCode:
          type: string
          example: "13232"
    CustomerInput:
      type: object
      properties:
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          example: "johndoe@email.com"
        document:
          type: string
          example: "12345"
        phone:
          type: string
          example: "11211244545"
        birthdate:
          type: string
          format: date
          example: "1991-07-05"
        promotionNotificationsAllowed:
          type: boolean
          example: false
        address:
          $ref: "#/components/schemas/Address"
    CustomerUpdateInput:
      type: object
      properties:
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        phone:
          type: string
          example: "11211244545"
        promotionNotificationsAllowed:
          type: boolean
          example: false
        address:
          $ref: "#/components/schemas/Address"


